DBCC DROPCLEANBUFFERS

DBCC FREEPROCCACHE --SUBSET OF BELOW FREESYSTEMCACHE

--MORE HARDCORE THAN FREEPROCCACHE - Compare this to FREEPROCCACHE: "Removes all elements from the plan cache...". This only affects the CACHESTORE_OBJCP and CACHESTORE_SQLCP caches.
DBCC FREESYSTEMCACHE ('ALL') WITH MARK_IN_USE_FOR_REMOVAL; --THIS PARAM MARKS EVERYTHING NOT FREED STRAIGHT AWAY TO BE DROPPED WHEN IT BECOMES AVAILABLE

--VIEW POTENTIAL CACHES TO FREE INDIVIDUALLY
SELECT DISTINCT TYPE FROM SYS.DM_OS_MEMORY_CACHE_COUNTERS 
DBCC FREESYSTEMCACHE('TokenAndPermUserStore') --SELECTIVELY FREEING ONLY A SINGLE CACHE