USE [TraceDB];
SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

BEGIN TRANSACTION;
INSERT INTO [dbo].[OLAPProfilerEventSubClass]([EventClassID], [EventSubClassID], [Name])
SELECT 4, 1, N'Instance Shutdown' UNION ALL
SELECT 4, 2, N'Instance Started' UNION ALL
SELECT 4, 3, N'Instance Paused' UNION ALL
SELECT 4, 4, N'Instance Continued' UNION ALL
SELECT 5, 1, N'Process' UNION ALL
SELECT 5, 2, N'Merge' UNION ALL
SELECT 5, 3, N'Delete' UNION ALL
SELECT 5, 4, N'DeleteOldAggregations' UNION ALL
SELECT 5, 5, N'Rebuild' UNION ALL
SELECT 5, 6, N'Commit' UNION ALL
SELECT 5, 7, N'Rollback' UNION ALL
SELECT 5, 8, N'CreateIndexes' UNION ALL
SELECT 5, 9, N'CreateTable' UNION ALL
SELECT 5, 10, N'InsertInto' UNION ALL
SELECT 5, 11, N'Transaction' UNION ALL
SELECT 5, 12, N'Initialize' UNION ALL
SELECT 5, 13, N'Discretize' UNION ALL
SELECT 5, 14, N'Query' UNION ALL
SELECT 5, 15, N'CreateView' UNION ALL
SELECT 5, 16, N'WriteData' UNION ALL
SELECT 5, 17, N'ReadData' UNION ALL
SELECT 5, 18, N'GroupData' UNION ALL
SELECT 5, 19, N'GroupDataRecord' UNION ALL
SELECT 5, 20, N'BuildIndex' UNION ALL
SELECT 5, 21, N'Aggregate' UNION ALL
SELECT 5, 22, N'BuildDecode' UNION ALL
SELECT 5, 23, N'WriteDecode' UNION ALL
SELECT 5, 24, N'BuildDMDecode' UNION ALL
SELECT 5, 25, N'ExecuteSQL' UNION ALL
SELECT 5, 26, N'ExecuteModifiedSQL' UNION ALL
SELECT 5, 27, N'Connecting' UNION ALL
SELECT 5, 28, N'BuildAggsAndIndexes' UNION ALL
SELECT 5, 29, N'MergeAggsOnDisk' UNION ALL
SELECT 5, 30, N'BuildIndexForRigidAggs' UNION ALL
SELECT 5, 31, N'BuildIndexForFlexibleAggs' UNION ALL
SELECT 5, 32, N'WriteAggsAndIndexes' UNION ALL
SELECT 5, 33, N'WriteSegment' UNION ALL
SELECT 5, 34, N'DataMiningProgress' UNION ALL
SELECT 5, 35, N'ReadBufferFullReport' UNION ALL
SELECT 5, 36, N'ProactiveCacheConversion' UNION ALL
SELECT 5, 37, N'Backup' UNION ALL
SELECT 5, 38, N'Restore' UNION ALL
SELECT 5, 39, N'Synchronize' UNION ALL
SELECT 5, 40, N'Build Processing Schedule' UNION ALL
SELECT 6, 1, N'Process' UNION ALL
SELECT 6, 2, N'Merge' UNION ALL
SELECT 6, 3, N'Delete' UNION ALL
SELECT 6, 4, N'DeleteOldAggregations' UNION ALL
SELECT 6, 5, N'Rebuild' UNION ALL
SELECT 6, 6, N'Commit'
COMMIT;
RAISERROR (N'[dbo].[OLAPProfilerEventSubClass]: Insert Batch: 1.....Done!', 10, 1) WITH NOWAIT;
GO

BEGIN TRANSACTION;
INSERT INTO [dbo].[OLAPProfilerEventSubClass]([EventClassID], [EventSubClassID], [Name])
SELECT 6, 7, N'Rollback' UNION ALL
SELECT 6, 8, N'CreateIndexes' UNION ALL
SELECT 6, 9, N'CreateTable' UNION ALL
SELECT 6, 10, N'InsertInto' UNION ALL
SELECT 6, 11, N'Transaction' UNION ALL
SELECT 6, 12, N'Initialize' UNION ALL
SELECT 6, 13, N'Discretize' UNION ALL
SELECT 6, 14, N'Query' UNION ALL
SELECT 6, 15, N'CreateView' UNION ALL
SELECT 6, 16, N'WriteData' UNION ALL
SELECT 6, 17, N'ReadData' UNION ALL
SELECT 6, 18, N'GroupData' UNION ALL
SELECT 6, 19, N'GroupDataRecord' UNION ALL
SELECT 6, 20, N'BuildIndex' UNION ALL
SELECT 6, 21, N'Aggregate' UNION ALL
SELECT 6, 22, N'BuildDecode' UNION ALL
SELECT 6, 23, N'WriteDecode' UNION ALL
SELECT 6, 24, N'BuildDMDecode' UNION ALL
SELECT 6, 25, N'ExecuteSQL' UNION ALL
SELECT 6, 26, N'ExecuteModifiedSQL' UNION ALL
SELECT 6, 27, N'Connecting' UNION ALL
SELECT 6, 28, N'BuildAggsAndIndexes' UNION ALL
SELECT 6, 29, N'MergeAggsOnDisk' UNION ALL
SELECT 6, 30, N'BuildIndexForRigidAggs' UNION ALL
SELECT 6, 31, N'BuildIndexForFlexibleAggs' UNION ALL
SELECT 6, 32, N'WriteAggsAndIndexes' UNION ALL
SELECT 6, 33, N'WriteSegment' UNION ALL
SELECT 6, 34, N'DataMiningProgress' UNION ALL
SELECT 6, 35, N'ReadBufferFullReport' UNION ALL
SELECT 6, 36, N'ProactiveCacheConversion' UNION ALL
SELECT 6, 37, N'Backup' UNION ALL
SELECT 6, 38, N'Restore' UNION ALL
SELECT 6, 39, N'Synchronize' UNION ALL
SELECT 6, 40, N'Build Processing Schedule' UNION ALL
SELECT 7, 1, N'Process' UNION ALL
SELECT 7, 2, N'Merge' UNION ALL
SELECT 7, 3, N'Delete' UNION ALL
SELECT 7, 4, N'DeleteOldAggregations' UNION ALL
SELECT 7, 5, N'Rebuild' UNION ALL
SELECT 7, 6, N'Commit' UNION ALL
SELECT 7, 7, N'Rollback' UNION ALL
SELECT 7, 8, N'CreateIndexes' UNION ALL
SELECT 7, 9, N'CreateTable' UNION ALL
SELECT 7, 10, N'InsertInto' UNION ALL
SELECT 7, 11, N'Transaction' UNION ALL
SELECT 7, 12, N'Initialize' UNION ALL
SELECT 7, 13, N'Discretize' UNION ALL
SELECT 7, 14, N'Query' UNION ALL
SELECT 7, 15, N'CreateView' UNION ALL
SELECT 7, 16, N'WriteData'
COMMIT;
RAISERROR (N'[dbo].[OLAPProfilerEventSubClass]: Insert Batch: 2.....Done!', 10, 1) WITH NOWAIT;
GO

BEGIN TRANSACTION;
INSERT INTO [dbo].[OLAPProfilerEventSubClass]([EventClassID], [EventSubClassID], [Name])
SELECT 7, 17, N'ReadData' UNION ALL
SELECT 7, 18, N'GroupData' UNION ALL
SELECT 7, 19, N'GroupDataRecord' UNION ALL
SELECT 7, 20, N'BuildIndex' UNION ALL
SELECT 7, 21, N'Aggregate' UNION ALL
SELECT 7, 22, N'BuildDecode' UNION ALL
SELECT 7, 23, N'WriteDecode' UNION ALL
SELECT 7, 24, N'BuildDMDecode' UNION ALL
SELECT 7, 25, N'ExecuteSQL' UNION ALL
SELECT 7, 26, N'ExecuteModifiedSQL' UNION ALL
SELECT 7, 27, N'Connecting' UNION ALL
SELECT 7, 28, N'BuildAggsAndIndexes' UNION ALL
SELECT 7, 29, N'MergeAggsOnDisk' UNION ALL
SELECT 7, 30, N'BuildIndexForRigidAggs' UNION ALL
SELECT 7, 31, N'BuildIndexForFlexibleAggs' UNION ALL
SELECT 7, 32, N'WriteAggsAndIndexes' UNION ALL
SELECT 7, 33, N'WriteSegment' UNION ALL
SELECT 7, 34, N'DataMiningProgress' UNION ALL
SELECT 7, 35, N'ReadBufferFullReport' UNION ALL
SELECT 7, 36, N'ProactiveCacheConversion' UNION ALL
SELECT 7, 37, N'Backup' UNION ALL
SELECT 7, 38, N'Restore' UNION ALL
SELECT 7, 39, N'Synchronize' UNION ALL
SELECT 7, 40, N'Build Processing Schedule' UNION ALL
SELECT 8, 1, N'Process' UNION ALL
SELECT 8, 2, N'Merge' UNION ALL
SELECT 8, 3, N'Delete' UNION ALL
SELECT 8, 4, N'DeleteOldAggregations' UNION ALL
SELECT 8, 5, N'Rebuild' UNION ALL
SELECT 8, 6, N'Commit' UNION ALL
SELECT 8, 7, N'Rollback' UNION ALL
SELECT 8, 8, N'CreateIndexes' UNION ALL
SELECT 8, 9, N'CreateTable' UNION ALL
SELECT 8, 10, N'InsertInto' UNION ALL
SELECT 8, 11, N'Transaction' UNION ALL
SELECT 8, 12, N'Initialize' UNION ALL
SELECT 8, 13, N'Discretize' UNION ALL
SELECT 8, 14, N'Query' UNION ALL
SELECT 8, 15, N'CreateView' UNION ALL
SELECT 8, 16, N'WriteData' UNION ALL
SELECT 8, 17, N'ReadData' UNION ALL
SELECT 8, 18, N'GroupData' UNION ALL
SELECT 8, 19, N'GroupDataRecord' UNION ALL
SELECT 8, 20, N'BuildIndex' UNION ALL
SELECT 8, 21, N'Aggregate' UNION ALL
SELECT 8, 22, N'BuildDecode' UNION ALL
SELECT 8, 23, N'WriteDecode' UNION ALL
SELECT 8, 24, N'BuildDMDecode' UNION ALL
SELECT 8, 25, N'ExecuteSQL' UNION ALL
SELECT 8, 26, N'ExecuteModifiedSQL'
COMMIT;
RAISERROR (N'[dbo].[OLAPProfilerEventSubClass]: Insert Batch: 3.....Done!', 10, 1) WITH NOWAIT;
GO

BEGIN TRANSACTION;
INSERT INTO [dbo].[OLAPProfilerEventSubClass]([EventClassID], [EventSubClassID], [Name])
SELECT 8, 27, N'Connecting' UNION ALL
SELECT 8, 28, N'BuildAggsAndIndexes' UNION ALL
SELECT 8, 29, N'MergeAggsOnDisk' UNION ALL
SELECT 8, 30, N'BuildIndexForRigidAggs' UNION ALL
SELECT 8, 31, N'BuildIndexForFlexibleAggs' UNION ALL
SELECT 8, 32, N'WriteAggsAndIndexes' UNION ALL
SELECT 8, 33, N'WriteSegment' UNION ALL
SELECT 8, 34, N'DataMiningProgress' UNION ALL
SELECT 8, 35, N'ReadBufferFullReport' UNION ALL
SELECT 8, 36, N'ProactiveCacheConversion' UNION ALL
SELECT 8, 37, N'Backup' UNION ALL
SELECT 8, 38, N'Restore' UNION ALL
SELECT 8, 39, N'Synchronize' UNION ALL
SELECT 8, 40, N'Build Processing Schedule' UNION ALL
SELECT 9, 0, N'MDXQuery' UNION ALL
SELECT 9, 1, N'DMXQuery' UNION ALL
SELECT 9, 2, N'SQLQuery' UNION ALL
SELECT 10, 0, N'MDXQuery' UNION ALL
SELECT 10, 1, N'DMXQuery' UNION ALL
SELECT 10, 2, N'SQLQuery' UNION ALL
SELECT 11, 1, N'Cache data' UNION ALL
SELECT 11, 2, N'Non-cache data' UNION ALL
SELECT 11, 3, N'Internal data' UNION ALL
SELECT 11, 4, N'SQL data' UNION ALL
SELECT 11, 11, N'Measure Group Structural Change' UNION ALL
SELECT 11, 12, N'Measure Group Deletion' UNION ALL
SELECT 12, 21, N'Cache data' UNION ALL
SELECT 12, 22, N'Non-cache data' UNION ALL
SELECT 12, 23, N'Internal data' UNION ALL
SELECT 12, 24, N'SQL data' UNION ALL
SELECT 15, 0, N'Create' UNION ALL
SELECT 15, 1, N'Alter' UNION ALL
SELECT 15, 2, N'Delete' UNION ALL
SELECT 15, 3, N'Process' UNION ALL
SELECT 15, 4, N'DesignAggregations' UNION ALL
SELECT 15, 5, N'WBInsert' UNION ALL
SELECT 15, 6, N'WBUpdate' UNION ALL
SELECT 15, 7, N'WBDelete' UNION ALL
SELECT 15, 8, N'Backup' UNION ALL
SELECT 15, 9, N'Restore' UNION ALL
SELECT 15, 10, N'MergePartitions' UNION ALL
SELECT 15, 11, N'Subscribe' UNION ALL
SELECT 15, 12, N'Batch' UNION ALL
SELECT 15, 13, N'BeginTransaction' UNION ALL
SELECT 15, 14, N'CommitTransaction' UNION ALL
SELECT 15, 15, N'RollbackTransaction' UNION ALL
SELECT 15, 16, N'GetTransactionState' UNION ALL
SELECT 15, 17, N'Cancel' UNION ALL
SELECT 15, 18, N'Synchronize' UNION ALL
SELECT 15, 19, N'Import80MiningModels'
COMMIT;
RAISERROR (N'[dbo].[OLAPProfilerEventSubClass]: Insert Batch: 4.....Done!', 10, 1) WITH NOWAIT;
GO

BEGIN TRANSACTION;
INSERT INTO [dbo].[OLAPProfilerEventSubClass]([EventClassID], [EventSubClassID], [Name])
SELECT 15, 10000, N'Other' UNION ALL
SELECT 16, 0, N'Create' UNION ALL
SELECT 16, 1, N'Alter' UNION ALL
SELECT 16, 2, N'Delete' UNION ALL
SELECT 16, 3, N'Process' UNION ALL
SELECT 16, 4, N'DesignAggregations' UNION ALL
SELECT 16, 5, N'WBInsert' UNION ALL
SELECT 16, 6, N'WBUpdate' UNION ALL
SELECT 16, 7, N'WBDelete' UNION ALL
SELECT 16, 8, N'Backup' UNION ALL
SELECT 16, 9, N'Restore' UNION ALL
SELECT 16, 10, N'MergePartitions' UNION ALL
SELECT 16, 11, N'Subscribe' UNION ALL
SELECT 16, 12, N'Batch' UNION ALL
SELECT 16, 13, N'BeginTransaction' UNION ALL
SELECT 16, 14, N'CommitTransaction' UNION ALL
SELECT 16, 15, N'RollbackTransaction' UNION ALL
SELECT 16, 16, N'GetTransactionState' UNION ALL
SELECT 16, 17, N'Cancel' UNION ALL
SELECT 16, 18, N'Synchronize' UNION ALL
SELECT 16, 19, N'Import80MiningModels' UNION ALL
SELECT 16, 10000, N'Other' UNION ALL
SELECT 19, 1, N'Backup' UNION ALL
SELECT 19, 2, N'Restore' UNION ALL
SELECT 19, 3, N'Synchronize' UNION ALL
SELECT 33, 1, N'DISCOVER_CONNECTIONS' UNION ALL
SELECT 33, 2, N'DISCOVER_SESSIONS' UNION ALL
SELECT 33, 3, N'DISCOVER_TRANSACTIONS' UNION ALL
SELECT 33, 6, N'DISCOVER_DB_CONNECTIONS' UNION ALL
SELECT 33, 7, N'DISCOVER_JOBS' UNION ALL
SELECT 33, 8, N'DISCOVER_LOCKS' UNION ALL
SELECT 33, 12, N'DISCOVER_PERFORMANCE_COUNTERS' UNION ALL
SELECT 33, 13, N'DISCOVER_MEMORYUSAGE' UNION ALL
SELECT 33, 14, N'DISCOVER_JOB_PROGRESS' UNION ALL
SELECT 33, 15, N'DISCOVER_MEMORYGRANT' UNION ALL
SELECT 34, 1, N'DISCOVER_CONNECTIONS' UNION ALL
SELECT 34, 2, N'DISCOVER_SESSIONS' UNION ALL
SELECT 34, 3, N'DISCOVER_TRANSACTIONS' UNION ALL
SELECT 34, 6, N'DISCOVER_DB_CONNECTIONS' UNION ALL
SELECT 34, 7, N'DISCOVER_JOBS' UNION ALL
SELECT 34, 8, N'DISCOVER_LOCKS' UNION ALL
SELECT 34, 12, N'DISCOVER_PERFORMANCE_COUNTERS' UNION ALL
SELECT 34, 13, N'DISCOVER_MEMORYUSAGE' UNION ALL
SELECT 34, 14, N'DISCOVER_JOB_PROGRESS' UNION ALL
SELECT 34, 15, N'DISCOVER_MEMORYGRANT' UNION ALL
SELECT 35, 1, N'DISCOVER_CONNECTIONS' UNION ALL
SELECT 35, 2, N'DISCOVER_SESSIONS' UNION ALL
SELECT 35, 3, N'DISCOVER_TRANSACTIONS' UNION ALL
SELECT 35, 6, N'DISCOVER_DB_CONNECTIONS' UNION ALL
SELECT 35, 7, N'DISCOVER_JOBS'
COMMIT;
RAISERROR (N'[dbo].[OLAPProfilerEventSubClass]: Insert Batch: 5.....Done!', 10, 1) WITH NOWAIT;
GO

BEGIN TRANSACTION;
INSERT INTO [dbo].[OLAPProfilerEventSubClass]([EventClassID], [EventSubClassID], [Name])
SELECT 35, 8, N'DISCOVER_LOCKS' UNION ALL
SELECT 35, 12, N'DISCOVER_PERFORMANCE_COUNTERS' UNION ALL
SELECT 35, 13, N'DISCOVER_MEMORYUSAGE' UNION ALL
SELECT 35, 14, N'DISCOVER_JOB_PROGRESS' UNION ALL
SELECT 35, 15, N'DISCOVER_MEMORYGRANT' UNION ALL
SELECT 36, 0, N'DBSCHEMA_CATALOGS' UNION ALL
SELECT 36, 1, N'DBSCHEMA_TABLES' UNION ALL
SELECT 36, 2, N'DBSCHEMA_COLUMNS' UNION ALL
SELECT 36, 3, N'DBSCHEMA_PROVIDER_TYPES' UNION ALL
SELECT 36, 4, N'MDSCHEMA_CUBES' UNION ALL
SELECT 36, 5, N'MDSCHEMA_DIMENSIONS' UNION ALL
SELECT 36, 6, N'MDSCHEMA_HIERARCHIES' UNION ALL
SELECT 36, 7, N'MDSCHEMA_LEVELS' UNION ALL
SELECT 36, 8, N'MDSCHEMA_MEASURES' UNION ALL
SELECT 36, 9, N'MDSCHEMA_PROPERTIES' UNION ALL
SELECT 36, 10, N'MDSCHEMA_MEMBERS' UNION ALL
SELECT 36, 11, N'MDSCHEMA_FUNCTIONS' UNION ALL
SELECT 36, 12, N'MDSCHEMA_ACTIONS' UNION ALL
SELECT 36, 13, N'MDSCHEMA_SETS' UNION ALL
SELECT 36, 14, N'DISCOVER_INSTANCES' UNION ALL
SELECT 36, 15, N'MDSCHEMA_KPIS' UNION ALL
SELECT 36, 16, N'MDSCHEMA_MEASUREGROUPS' UNION ALL
SELECT 36, 17, N'MDSCHEMA_COMMANDS' UNION ALL
SELECT 36, 18, N'DMSCHEMA_MINING_SERVICES' UNION ALL
SELECT 36, 19, N'DMSCHEMA_MINING_SERVICE_PARAMETERS' UNION ALL
SELECT 36, 20, N'DMSCHEMA_MINING_FUNCTIONS' UNION ALL
SELECT 36, 21, N'DMSCHEMA_MINING_MODEL_CONTENT' UNION ALL
SELECT 36, 22, N'DMSCHEMA_MINING_MODEL_XML' UNION ALL
SELECT 36, 23, N'DMSCHEMA_MINING_MODELS' UNION ALL
SELECT 36, 24, N'DMSCHEMA_MINING_COLUMNS' UNION ALL
SELECT 36, 25, N'DISCOVER_DATASOURCES' UNION ALL
SELECT 36, 26, N'DISCOVER_PROPERTIES' UNION ALL
SELECT 36, 27, N'DISCOVER_SCHEMA_ROWSETS' UNION ALL
SELECT 36, 28, N'DISCOVER_ENUMERATORS' UNION ALL
SELECT 36, 29, N'DISCOVER_KEYWORDS' UNION ALL
SELECT 36, 30, N'DISCOVER_LITERALS' UNION ALL
SELECT 36, 31, N'DISCOVER_XML_METADATA' UNION ALL
SELECT 36, 32, N'DISCOVER_TRACES' UNION ALL
SELECT 36, 33, N'DISCOVER_TRACE_DEFINITION_PROVIDERINFO' UNION ALL
SELECT 36, 34, N'DISCOVER_TRACE_COLUMNS' UNION ALL
SELECT 36, 35, N'DISCOVER_TRACE_EVENT_CATEGORIES' UNION ALL
SELECT 36, 36, N'DMSCHEMA_MINING_STRUCTURES' UNION ALL
SELECT 36, 37, N'DMSCHEMA_MINING_STRUCTURE_COLUMNS' UNION ALL
SELECT 36, 38, N'DISCOVER_MASTER_KEY' UNION ALL
SELECT 36, 39, N'MDSCHEMA_INPUT_DATASOURCES' UNION ALL
SELECT 36, 40, N'DISCOVER_LOCATIONS' UNION ALL
SELECT 36, 41, N'DISCOVER_PARTITION_DIMENSION_STAT' UNION ALL
SELECT 36, 42, N'DISCOVER_PARTITION_STAT' UNION ALL
SELECT 36, 43, N'DISCOVER_DIMENSION_STAT' UNION ALL
SELECT 38, 0, N'DBSCHEMA_CATALOGS'
COMMIT;
RAISERROR (N'[dbo].[OLAPProfilerEventSubClass]: Insert Batch: 6.....Done!', 10, 1) WITH NOWAIT;
GO

BEGIN TRANSACTION;
INSERT INTO [dbo].[OLAPProfilerEventSubClass]([EventClassID], [EventSubClassID], [Name])
SELECT 38, 1, N'DBSCHEMA_TABLES' UNION ALL
SELECT 38, 2, N'DBSCHEMA_COLUMNS' UNION ALL
SELECT 38, 3, N'DBSCHEMA_PROVIDER_TYPES' UNION ALL
SELECT 38, 4, N'MDSCHEMA_CUBES' UNION ALL
SELECT 38, 5, N'MDSCHEMA_DIMENSIONS' UNION ALL
SELECT 38, 6, N'MDSCHEMA_HIERARCHIES' UNION ALL
SELECT 38, 7, N'MDSCHEMA_LEVELS' UNION ALL
SELECT 38, 8, N'MDSCHEMA_MEASURES' UNION ALL
SELECT 38, 9, N'MDSCHEMA_PROPERTIES' UNION ALL
SELECT 38, 10, N'MDSCHEMA_MEMBERS' UNION ALL
SELECT 38, 11, N'MDSCHEMA_FUNCTIONS' UNION ALL
SELECT 38, 12, N'MDSCHEMA_ACTIONS' UNION ALL
SELECT 38, 13, N'MDSCHEMA_SETS' UNION ALL
SELECT 38, 14, N'DISCOVER_INSTANCES' UNION ALL
SELECT 38, 15, N'MDSCHEMA_KPIS' UNION ALL
SELECT 38, 16, N'MDSCHEMA_MEASUREGROUPS' UNION ALL
SELECT 38, 17, N'MDSCHEMA_COMMANDS' UNION ALL
SELECT 38, 18, N'DMSCHEMA_MINING_SERVICES' UNION ALL
SELECT 38, 19, N'DMSCHEMA_MINING_SERVICE_PARAMETERS' UNION ALL
SELECT 38, 20, N'DMSCHEMA_MINING_FUNCTIONS' UNION ALL
SELECT 38, 21, N'DMSCHEMA_MINING_MODEL_CONTENT' UNION ALL
SELECT 38, 22, N'DMSCHEMA_MINING_MODEL_XML' UNION ALL
SELECT 38, 23, N'DMSCHEMA_MINING_MODELS' UNION ALL
SELECT 38, 24, N'DMSCHEMA_MINING_COLUMNS' UNION ALL
SELECT 38, 25, N'DISCOVER_DATASOURCES' UNION ALL
SELECT 38, 26, N'DISCOVER_PROPERTIES' UNION ALL
SELECT 38, 27, N'DISCOVER_SCHEMA_ROWSETS' UNION ALL
SELECT 38, 28, N'DISCOVER_ENUMERATORS' UNION ALL
SELECT 38, 29, N'DISCOVER_KEYWORDS' UNION ALL
SELECT 38, 30, N'DISCOVER_LITERALS' UNION ALL
SELECT 38, 31, N'DISCOVER_XML_METADATA' UNION ALL
SELECT 38, 32, N'DISCOVER_TRACES' UNION ALL
SELECT 38, 33, N'DISCOVER_TRACE_DEFINITION_PROVIDERINFO' UNION ALL
SELECT 38, 34, N'DISCOVER_TRACE_COLUMNS' UNION ALL
SELECT 38, 35, N'DISCOVER_TRACE_EVENT_CATEGORIES' UNION ALL
SELECT 38, 36, N'DMSCHEMA_MINING_STRUCTURES' UNION ALL
SELECT 38, 37, N'DMSCHEMA_MINING_STRUCTURE_COLUMNS' UNION ALL
SELECT 38, 38, N'DISCOVER_MASTER_KEY' UNION ALL
SELECT 38, 39, N'MDSCHEMA_INPUT_DATASOURCES' UNION ALL
SELECT 38, 40, N'DISCOVER_LOCATIONS' UNION ALL
SELECT 39, 0, N'Proactive Caching Begin' UNION ALL
SELECT 39, 1, N'Proactive Caching End' UNION ALL
SELECT 39, 2, N'Flight Recorder Started' UNION ALL
SELECT 39, 3, N'Flight Recorder Stopped' UNION ALL
SELECT 39, 4, N'Configuration Properties Updated' UNION ALL
SELECT 39, 5, N'SQL Trace' UNION ALL
SELECT 39, 6, N'Object Created' UNION ALL
SELECT 39, 7, N'Object Deleted' UNION ALL
SELECT 39, 8, N'Object Altered' UNION ALL
SELECT 39, 9, N'Proactive Caching Polling Begin'
COMMIT;
RAISERROR (N'[dbo].[OLAPProfilerEventSubClass]: Insert Batch: 7.....Done!', 10, 1) WITH NOWAIT;
GO

BEGIN TRANSACTION;
INSERT INTO [dbo].[OLAPProfilerEventSubClass]([EventClassID], [EventSubClassID], [Name])
SELECT 39, 10, N'Proactive Caching Polling End' UNION ALL
SELECT 39, 11, N'Flight Recorder Snapshot Begin' UNION ALL
SELECT 39, 12, N'Flight Recorder Snapshot End' UNION ALL
SELECT 39, 13, N'Proactive Caching: notifiable object updated' UNION ALL
SELECT 39, 14, N'Lazy Processing: start processing' UNION ALL
SELECT 39, 15, N'Lazy Processing: processing complete' UNION ALL
SELECT 61, 1, N'Get data from measure group cache' UNION ALL
SELECT 61, 2, N'Get data from flat cache' UNION ALL
SELECT 61, 3, N'Get data from calculation cache' UNION ALL
SELECT 61, 4, N'Get data from persisted cache' UNION ALL
SELECT 73, 1, N'Get Data' UNION ALL
SELECT 73, 2, N'Process Calculated Members' UNION ALL
SELECT 73, 3, N'Post Order' UNION ALL
SELECT 76, 1, N'Serialize Axes' UNION ALL
SELECT 76, 2, N'Serialize Cells' UNION ALL
SELECT 76, 3, N'Serialize SQL Rowset' UNION ALL
SELECT 76, 4, N'Serialize Flattened Rowset' UNION ALL
SELECT 81, 1, N'Cache data' UNION ALL
SELECT 81, 2, N'Non-cache data'
COMMIT;
RAISERROR (N'[dbo].[OLAPProfilerEventSubClass]: Insert Batch: 8.....Done!', 10, 1) WITH NOWAIT;
GO

